### ISSUE TITLE
Blog article: image goes out of text-box

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-rotterdam#20]
If I add some big image to text block, then result is:
![screen shot 2015-12-03 at 12 29 29](https://cloud.githubusercontent.com/assets/13623224/11558263/539beb1c-99ba-11e5-977f-951dca2c60ac.png)

**Comment by kaspar-naaber** [comment]
That's the expected behaviour in this template. Image that is set as wide as the content area, becomes wider than the content area.
