### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-rotterdam#23]

**Comment by SSirjes** [comment]
* [ ] **Mobile menu has default some design editor values?**

![screen shot 2016-05-10 at 16 31 27](https://cloud.githubusercontent.com/assets/13623224/15148609/af69b1ea-16ce-11e6-9f03-9cd700e391a7.png)

_Original mobile menu_
![screen shot 2016-05-10 at 16 35 14](https://cloud.githubusercontent.com/assets/13623224/15148479/17cede32-16ce-11e6-89a5-f4c7dca4e272.png)
